on: [push, pull_request]

jobs:
  macos:
    uses: lotem/librime/.github/workflows/macos-build.yml@master
    with:
      repository: lotem/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}

  windows:
    uses: lotem/librime/.github/workflows/windows-build.yml@master
    with:
      repository: lotem/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }}
